drop table if exists animals cascade;
create table animals
(
	animal_id serial primary key,
	breed text not null check(length(breed) >0 ),
	weight1 float not null check(weight1 >= 0 and weight1<500),
	age float not null check(age >0 and age <100)
);

comment on table animals is 'Information of the animals.';
comment on column animals.animal_id is 'The Animal autogenerated ID.';
comment on column animals.breed is 'The breed of the animal.';
comment on column animals.weight1 is 'The weight of the animal';
comment on column animals.age is 'The age of the animal';
grant select, insert, update, delete on table animals to "Assignment2";